### ISSUE TITLE
storybook knobs testing?

### ISSUE THREAD

**Issue by evexoio** [oblador/loki#120]
Can we add storybook testing for knobs?

I know this might be a big change, I want to know what you think about implementing automatic testing for storybook knobs.

Thanks

**Comment by tr00st** [comment]
Might be worth noting that there's a successor to the Knobs addon:

https://github.com/storybookjs/storybook/issues/8614#issuecomment-635502840
https://github.com/storybookjs/storybook/tree/next/addons/controls#how-will-this-replace-addon-knobs

The deprecation of Knobs won't be especially quick, but might be worth considering starting with Controls instead of implementing the integration twice...

**Comment by hydra13** [comment]
Okay, and what about Controls? Can Loki use different states of Controls during tests?

**Comment by techeverri** [comment]
If you have more ideas or comments, please create a discussion.
- https://github.com/oblador/loki/discussions
