### ISSUE TITLE
[Feature request] Delay before taking a screenshot

### ISSUE THREAD

**Issue by RikuMantysalo** [oblador/loki#145]
Hello,

I am having issues with tests failing, as the loading time of my components is not consistent with each render.

Is there a way to add a delay for the screenshot taking, so that I can ensure that the components are completely rendered before the screenshot is taken?

**Comment by techeverri** [comment]
Hey @RikuMantysalo

Have you tried the the command line flag `--chromeLoadTimeout`?
https://loki.js.org/command-line-arguments.html

**Comment by RikuMantysalo** [comment]
> Hey @RikuMantysalo
> 
> Have you tried the the command line flag `--chromeLoadTimeout`?
> https://loki.js.org/command-line-arguments.html

Hey @techeverri, it seems that this command line flag is for the time that Loki waits for a 200 HTTP response from the storybook server before timing out and not the time that it waits before the screenshots.

I managed to add a quick hack to `create-chrome-target.js`with

```javascript
// Basic sleep function
 function sleep(ms) {
    console.log("sleeping for" + ms);
    return new Promise(resolve => setTimeout(resolve, ms));
  }

async function captureScreenshotForStory(kind, story, outputPath, options, configuration) {
...
    try {
      await withTimeout(options.chromeLoadTimeout)(tab.loadUrl(url));
      await sleep(configuration.delay); // Hack
      screenshot = await tab.captureScreenshot(selector);
      await fs.outputFile(outputPath, screenshot);
    }
...
}
```

but a more sophisticated solution would be nice.

**Comment by oblador** [comment]
You can make your story async to take the screenshot whenever you like, see https://loki.js.org/flaky-tests.html#asynchronous-stories

**Comment by jalooc** [comment]
@oblador `lokiAsync` is a good workaround, but I'm pretty sure that loki isn't waiting for the component to fully render (at least in React Native).

I have one _heavier_ component doing nothing async - simply containing many nodes, for which in 9 out of 10 test runs, the generated screenshot is for _the previous_ story. This indicates that the component in questions doesn't finish rendering before the screenshot is taken. I have to proofs for that:
1. manual switching between the stories does feel slower when opening the story with that component,
2. the problem disappeared when I used `lokiAsync`, added `useEffect()` to that component and executed `done()` in it.

My conclusion from that simple experiment is that loki should wait for the component to render, and therefore generate the screenshot either in some kind of loki's internal `useEffect` or `componentDidMount`. Does it sound good @oblador ?

**Comment by vitto** [comment]
I'm surprised this feature request is closed.

I have a scenario where I'm forced to skip various tests due to the missing `screenshotDelay` when the page loads mixed to the fact I'm using **web-components** with CSS animation from the **shadow DOM**. 

Since **web-components** have a **shadow DOM** it's impossible to disable CSS transitions by overriding `transition-duration` property via a global CSS selector, at the moment the only solution I've found is to skip the tests which fail due to an intro animation.

I would be forced to add a custom property in the **web-component** CSS, something like `--transition-duration`, create a dedicated test and set it to `0s` to avoid the problem. Maybe this isn't the best solution but it's an example how a `screenshotDelay` would simplify my life and avoid duplicated tests or component complexity.

Please consider re-open this feature request, I would be very happy to cover all my components.

**Comment by oblador** [comment]
@vitto You can easily implement this yourself by combining `createAsyncCallback` with `setTimeout`, but it's bad practice so I don't want to encourage it by adding it as a config.

**Comment by vitto** [comment]
Thanks for the workaround info, I'll take a look.

**Comment by vitto** [comment]
Do you mean this? https://loki.js.org/flaky-tests.html#asynchronous-stories

I would avoid this because I would be forced to implement specific behavior inside my components that are not meant to have.

I still think a property like `delay` from [BackstopJS](https://github.com/garris/BackstopJS#advanced-scenarios) would be the solution to problems like **shadow DOM** CSS transitions.

**Comment by oblador** [comment]
If you can make a minimal reproduction i can try to fix the shadow dom css transitions, but I'm very confident that adding blanket delay setting leads to slow tests and does not fix flakiness. You can implement delay for all your tests with a decorator if you want, but I don't want to support it in the framework for said reasons.
