### ISSUE TITLE
React Hook Error when running loki commands

### ISSUE THREAD

**Issue by nersoh** [oblador/loki#356]
Hi. After installing `loki`, I got errors regarding React Hooks. I couldn't find anything about it, so does it ring the bell of you what the cause would be or at least a lead towards how to debug it?

Thanks!

Versions
- Storybook: 6.4.9
- Loki: 0.28.1

<img width="1072" alt="Screenshot 2021-12-28 at 11 40 13" src="https://user-images.githubusercontent.com/1930729/147563462-137fbb67-de16-4734-a6ca-31b8e79dbccf.png">

**Comment by techeverri** [comment]
The error message is most likely coming from React itself. I don't think it has anything to with Loki.
But if you can replicate this error with an example project, it would make it easier to investigate.

Feel free to open a new bug report if you find something, otherwise I'd recommend you create a discussion in the https://github.com/oblador/loki/discussions for questions, comments or ideas

**Comment by euphocat** [comment]
Hello, sorry to comment again but I have the same error here while trying to update a project from React 16 to React 17.
I see in my call stack the problem occurs in `node_modules/@loki/runner/node_modules/react/cjs/react.development.js:1465:13` and the @loki/runner has a direct dependency to React@16 see `https://github.com/oblador/loki/blob/master/packages/runner/package.json`

**Comment by saphewilliam** [comment]
Hey! If you are still struggling with this, I got things to work by adding a resolution field to my package.json (I believe this only works with yarn package manager but not 100%
```json
"resolutions": {
    "react": "17.0.2" // or any other desired version of react
},
```
