### ISSUE TITLE
Access to script 'x' from origin 'null' has been blocked by CORS policy

### ISSUE THREAD

**Issue by yevgeniy-belov** [oblador/loki#416]
My setup:
- Storybook : v6.5.12
- Vite: 3.0.9
- React 18.2.0

Im running these commands:
`build-storybook`
`loki --requireReference --reactUri file:./storybook-static`

and Im getting this error inside Docker container:
`"Access to script at 'file:///assets/iframe.1ba845cc.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-untrusted, https.", source: file:///var/loki/iframe.html (378)`

Am I missing something?

**Comment by marduzca** [comment]
@yevgeniy-belov 
Hi there. Did you ever manage to solve this? I'm currently trying to run loki with Vite, but I cannot make it work. I don't reach the point that you do, I get and "chrome.docker ECONNREFUSED" error. Did you go through that already?
Maybe we can help each other to make it work? And maybe if we show that we are several people having issues with Vite @oblador will also take time to help us understand and fix the issue? I love Loki and it would be sad to have to drop it only because of switching to a different bundler

**Comment by yevgeniy-belov** [comment]
@marduzca unfortunately, not really. I switched to jest-image-snapshot + puppeteer but bumped in to the rendering discrepancies between local machines and Github Actions environments. So, I ended up declaring the "DIY" visual regressions as not worth it in my case...

**Comment by marduzca** [comment]
That's sad. I will try to make it work (hopefully with the help of @oblador ) and will let you know if manage to or even if I don't to let you know what alternative I took 👍🏼

**Comment by oblador** [comment]
To get around this you need to serve fonts via an http server. Latest version will do this, so just upgrade to 0.33.0
